### ISSUE TITLE
Create Helm packages and host them

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/udp#6]
To use Helm in the correct way, in the validation script example, we need to create Helm packages and host them.

The helm charts to be packaged are contained [here](https://github.com/packit/udp.git)

Serhii suggested us to follow this [guide](https://betterprogramming.pub/using-gitlab-as-helm-chart-registry-ab4d4ef42833)

Recap of repos used by the project:

source code repo: https://gitlab.cee.redhat.com/packit/validation-cronjob-script
helm charts repo: https://github.com/packit/udp.git dir: udp/ocp-helm-charts/packit-service-validation/
helm chart configuration: https://gitlab.cee.redhat.com/packit/validation-cronjob-script-deployment

Serhii worked on some projects we can use as examples.
_I've played a bit with helm packages. 
Created a Gitlab CI job that uploads a Helm Package to the repo:_

Doc: https://stackoverflow.com/collectives/gitlab/articles/72532380/using-gitlab-as-helm-chart-registry
Repo example: https://gitlab.com/sturivny/posting-helm-charts
Gitlab-ci file: https://gitlab.com/sturivny/posting-helm-charts/-/blob/main/.gitlab-ci.yml
Created package: https://gitlab.com/sturivny/posting-helm-charts/-/packages/9318125

**Comment by jpopelka** [comment]
I don't see why the chart repository can't be here on GitHub and needs to be in the internal Gitlab.
I guess I'll learn it the hard way - #8
